variable "route53_zone" {
  description = "The domain used in the URL"
  type        = string
}

variable "route53_subdomain" {
  description = "The subdomain of the URL"
  type        = string
}

variable "cert_email" {
  description = "Email address used to obtain SSL certificate"
  type        = string
}

variable "region" {
  type        = string
  description = "The region to deploy resources in"
}

variable "tfe_encryption_password" {
  description = "TFE encryption password"
  type        = string
}

variable "tfe_release" {
  description = "Which release version of TFE to install"
  type        = string
  default     = "v202406-1"
}

variable "tfe_license" {
  description = "Value from the License file"
  type        = string
  default     = "02MV4UU43BK5HGYYTOJZWFQMTMNNEWU33JLFVE252ZK5HG2TKEKF2E4RCONRHUGMBVJVDVCM2MKRVTCT2EM52FS2SJPJGTEVTMJV5FSNCNNVHG2SLJO5UVSM2WPJSEOOLULJMEUZTBK5IWST3JJJWE2VCNGJHFOTTKJVUTC2C2NJWGWTCUJE2U4VCBORGUITJVJVUTC3C2NJMTETTNKEYFSVCNO5MXUQLJJRBUU4DCNZHDAWKXPBZVSWCSOBRDENLGMFLVC2KPNFEXCSLJO5UWCWCOPJSFOVTGMRDWY5C2KNETMSLKJF3U22SNORGUI23UJVKEUVKNIRTTMTLKLE3E4VCBOVGWURLYJVKFCMKOIRRXSV3JJFZUS3SOGBMVQSRQLAZVE4DCK5KWST3JJF4U2RCJPJGFIQJVJRKEK6KWIRAXOT3KIF3U62SBO5LWSSLTJFWVMNDDI5WHSWKYKJYGEMRVMZSEO3DULJJUSNSJNJEXOTLKKV2E2RCFORGUIRSVJVCECNSNIRATMTKEIJQUS2LXNFSEOVTZMJLWY5KZLBJHAYRSGVTGIR3MORNFGSJWJFVES52NNJKXITKEIV2E2RCGKVGUIQJWJVCECNSNIRBGCSLJO5UWGSCKOZNEQVTKMRBUSNSJNZJGYY3OJJUFU3JZPFRFGSLTJFWVU42ZK5SHUSLKOA3WMWBQHUXGCQ3SM5MXA32VPB3GQTTJJJYFU2ZSKVMDO5DMKZBWOOJUIUVUCSRSJYYHU4LMOVSWS3LRPFLDIVDPF5EES3CFNYXUWTTFMR4WW4ZQNFEDCUSEGJVWMTKOMMYE4YJQINVXUSKEI5BDKMLEIFVWGYJUMRLDAMZTHBIHO3KWNRQXMSSQGRYEU6CJJE4UINSVIZGFKYKWKBVGWV2KORRUINTQMFWDM32PMZDW4SZSPJIEWSSSNVDUQVRTMVNHO4KGMUVW6N3LF5ZSWQKUJZUFAWTHKMXUWVSZM4XUWK3MI5IHOTBXNJBHQSJXI5HWC2ZWKVQWSYKIN5SWWMCSKRXTOMSEKE6T2"
}

variable "replica_count" {
  description = "Number of Pods/replicas"
  type        = string
  default     = "1"
}